### ISSUE TITLE
Eror WARNING - Minimum stake amount  !

### ISSUE THREAD

**Issue by batcandoi27** [stash86/freqtrade_stuff#2]
Hi !, I am using your dca code and have had many good results. But only with max_open_trade = 1, max_entry_position_adjustment = 3,"stake_amount": "unlimited".  The problem arises when changing max_open_trade = 4, it gives an error that cannot execute dca times for open pairs 2, 3, 4. When opening the first entry pair 1 one, not yet dca, and then opening entries 2, 3, 4, the amount of money opened for pair 2,3,4 will subtract the amount opened in pair 1 (not dca), but when it has been dca times. 1st, 2nd, 3rd of pair 1. This leads to not enough money to dca for pair 2, 3, 4. And error message:
**freqtrade.wallets: WARNING - Minimum stake amount > available balance. 1.5 > 0.05118996800001696**
I mean the return part _(proposed_stake / self.max_so_multiplier)_
in the function _def custom_stake_amount_ need to deduct the amount of the open transaction + Include the backup for dca this open transaction, then the above situation will not happen! But I don't know how to adjust!
**_Thanks for your great code!_**

**Comment by stash86** [comment]
Use this https://docs.google.com/spreadsheets/d/1-6XnQ7lmNphQALhKf00FCF7Bia-kZqM0cBuwroFfAU0/edit?usp=sharing

Fill the part in the `spot` tab, and see the summary. See how much needed per trading slot for how many extra entry you want

**Comment by batcandoi27** [comment]
Sorry for the lack of information, I am using it for futures market (5x), which means can enter with only 1$.
Is there any adjustment so that after the entry of open pair 1, the unordered amount in the first open 2 entry is deducted from the amount opened in pair 1+ include backup to dca #1, #2, #3 in pair 1, and the next time you open the open entry pair: you have deducted the unordered amount in the previous entries and the dca backups. I think the problem is that stack amount fix does not fail, but when stack amount = unlimit it fails !
Like the example shown, 100$ with max_open_trade = 4; At the time of opening tradeid #124, all shares were used up, then there was not enough dca for the opening of trade id #199 
https://ibb.co/my5MMcn

**Comment by batcandoi27** [comment]
Is there any adjustment so that after the entry of open pair 1, the unordered amount in the first open 2 entry is deducted from the amount opened in pair 1+ for backup to dca #1, #2, #3 in pair 1, and the next time you open the open entry pair: you have deducted the unordered amount in the previous entries and the dca backups. I think the problem is that stack amount fix does not fail, but when stack amount = unlimit it fails !

**Comment by batcandoi27** [comment]
''' stake_amount = filled_entries[0].stake_amount
Problem was fixed by this code in freqtrade new version ! '''
https://www.freqtrade.io/en/stable/strategy-callbacks/#adjust-trade-position

**Comment by chiragbansal10** [comment]
which strategy should i use for trading
